### ISSUE TITLE
Occasional get() error in /transport/timetable/

### ISSUE THREAD

**Issue by jw35** [SmartCambridge/tfc_web#260]
The logs are recording this occasionally:

```
2018-12-17 19:52:11,170] [django.request] [ERROR] - Internal Server Error: /transport/timetable/21-central-basildon-vange-pitsea-north-benfleet
Traceback (most recent call last):
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/views/generic/detail.py", line 115, in get
    self.object = self.get_object()
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/views/generic/detail.py", line 53, in get_object
    obj = queryset.get()
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/db/models/query.py", line 384, in get
    (self.model._meta.object_name, num)
transport.models.MultipleObjectsReturned: get() returned more than one Line -- it returned 2!
```

**Comment by jw35** [comment]
Fixed by #306
