### ISSUE TITLE
Can't delete CSN device

### ISSUE THREAD

**Issue by jw35** [SmartCambridge/tfc_web#276]
I can't delete my device 'Dev1'. Attempts to do so result in 'Server Error (500)' in the browser and the following in Gunicorn's log:

```
[2019-01-22 16:38:48,187] [CSN] [ERROR] - Everynet responded with a 404 status code and the following error message: {
    "error": "Device not found"
}
[2019-01-22 16:38:48,188] [django.request] [ERROR] - Internal Server Error: /csn/device/delete
Traceback (most recent call last):
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/tfc_prod/tfc_web/tfc_web/csn/views.py", line 61, in delete_device
    if everynet_remove_device(lwdevice):
  File "/home/tfc_prod/tfc_web/tfc_web/csn/everynet_api.py", line 58, in everynet_remove_device
    lwdev.error_message = response.json()['message']
KeyError: 'message'
```

There is a device with that DevEUI in the Everynet console, though I have been modifying the console entries so it's possible I've broken the CSN <-> Everynet correspondence. I've successfully created and deleted a second device so I don't know what's going on here.

**Comment by jw35** [comment]
I think the problem is that the CSN and the Everynet API will happily create a device if the DevEUI contains upper- and/or lower-case letters, but the Everynet API's DELETE endpoint only recognises DevEUIs containing lower-case letters. I'd created my device with an all upper-case DevEUI.

I've worked around the problem by temporally applying.lower() the the EUI in everynet_api.py and then removing it again. Perhaps canonicalising DevEUI on input to CSN would be a better long-term fix?

**Comment by jw35** [comment]
There's also obviously a problem that there's no 'message' key in the JSON returned on error.
